thresholds:
    median_minium: 1000
    quartile_range: [100, 10000]

reference: resources/references/NC_045512.2.fasta

sample_accession_file: config/sample_accessions.csv

data_saver_mode: false
job_grouping_mode: true
